// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteUsersNoContentCode is the HTTP code returned for type DeleteUsersNoContent
const DeleteUsersNoContentCode int = 204

/*
DeleteUsersNoContent No Content

swagger:response deleteUsersNoContent
*/
type DeleteUsersNoContent struct {
}

// NewDeleteUsersNoContent creates DeleteUsersNoContent with default headers values
func NewDeleteUsersNoContent() *DeleteUsersNoContent {

	return &DeleteUsersNoContent{}
}

// WriteResponse to the client
func (o *DeleteUsersNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteUsersBadRequestCode is the HTTP code returned for type DeleteUsersBadRequest
const DeleteUsersBadRequestCode int = 400

/*
DeleteUsersBadRequest Bad Request

swagger:response deleteUsersBadRequest
*/
type DeleteUsersBadRequest struct {
}

// NewDeleteUsersBadRequest creates DeleteUsersBadRequest with default headers values
func NewDeleteUsersBadRequest() *DeleteUsersBadRequest {

	return &DeleteUsersBadRequest{}
}

// WriteResponse to the client
func (o *DeleteUsersBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteUsersInternalServerErrorCode is the HTTP code returned for type DeleteUsersInternalServerError
const DeleteUsersInternalServerErrorCode int = 500

/*
DeleteUsersInternalServerError Internal Server Error

swagger:response deleteUsersInternalServerError
*/
type DeleteUsersInternalServerError struct {
}

// NewDeleteUsersInternalServerError creates DeleteUsersInternalServerError with default headers values
func NewDeleteUsersInternalServerError() *DeleteUsersInternalServerError {

	return &DeleteUsersInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteUsersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
