// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PatchUsersOKCode is the HTTP code returned for type PatchUsersOK
const PatchUsersOKCode int = 200

/*
PatchUsersOK OK

swagger:response patchUsersOK
*/
type PatchUsersOK struct {
}

// NewPatchUsersOK creates PatchUsersOK with default headers values
func NewPatchUsersOK() *PatchUsersOK {

	return &PatchUsersOK{}
}

// WriteResponse to the client
func (o *PatchUsersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PatchUsersBadRequestCode is the HTTP code returned for type PatchUsersBadRequest
const PatchUsersBadRequestCode int = 400

/*
PatchUsersBadRequest Bad Request

swagger:response patchUsersBadRequest
*/
type PatchUsersBadRequest struct {
}

// NewPatchUsersBadRequest creates PatchUsersBadRequest with default headers values
func NewPatchUsersBadRequest() *PatchUsersBadRequest {

	return &PatchUsersBadRequest{}
}

// WriteResponse to the client
func (o *PatchUsersBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PatchUsersInternalServerErrorCode is the HTTP code returned for type PatchUsersInternalServerError
const PatchUsersInternalServerErrorCode int = 500

/*
PatchUsersInternalServerError Internal Server Error

swagger:response patchUsersInternalServerError
*/
type PatchUsersInternalServerError struct {
}

// NewPatchUsersInternalServerError creates PatchUsersInternalServerError with default headers values
func NewPatchUsersInternalServerError() *PatchUsersInternalServerError {

	return &PatchUsersInternalServerError{}
}

// WriteResponse to the client
func (o *PatchUsersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
