// Code generated by go-swagger; DO NOT EDIT.

package notes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteNotesIDOKCode is the HTTP code returned for type DeleteNotesIDOK
const DeleteNotesIDOKCode int = 200

/*
DeleteNotesIDOK OK

swagger:response deleteNotesIdOK
*/
type DeleteNotesIDOK struct {
}

// NewDeleteNotesIDOK creates DeleteNotesIDOK with default headers values
func NewDeleteNotesIDOK() *DeleteNotesIDOK {

	return &DeleteNotesIDOK{}
}

// WriteResponse to the client
func (o *DeleteNotesIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteNotesIDBadRequestCode is the HTTP code returned for type DeleteNotesIDBadRequest
const DeleteNotesIDBadRequestCode int = 400

/*
DeleteNotesIDBadRequest Bad Request

swagger:response deleteNotesIdBadRequest
*/
type DeleteNotesIDBadRequest struct {
}

// NewDeleteNotesIDBadRequest creates DeleteNotesIDBadRequest with default headers values
func NewDeleteNotesIDBadRequest() *DeleteNotesIDBadRequest {

	return &DeleteNotesIDBadRequest{}
}

// WriteResponse to the client
func (o *DeleteNotesIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteNotesIDInternalServerErrorCode is the HTTP code returned for type DeleteNotesIDInternalServerError
const DeleteNotesIDInternalServerErrorCode int = 500

/*
DeleteNotesIDInternalServerError Internal Server Error

swagger:response deleteNotesIdInternalServerError
*/
type DeleteNotesIDInternalServerError struct {
}

// NewDeleteNotesIDInternalServerError creates DeleteNotesIDInternalServerError with default headers values
func NewDeleteNotesIDInternalServerError() *DeleteNotesIDInternalServerError {

	return &DeleteNotesIDInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteNotesIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
