// Code generated by go-swagger; DO NOT EDIT.

package notes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteNotesIDHandlerFunc turns a function with the right signature into a delete notes ID handler
type DeleteNotesIDHandlerFunc func(DeleteNotesIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteNotesIDHandlerFunc) Handle(params DeleteNotesIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteNotesIDHandler interface for that can handle valid delete notes ID params
type DeleteNotesIDHandler interface {
	Handle(DeleteNotesIDParams, interface{}) middleware.Responder
}

// NewDeleteNotesID creates a new http.Handler for the delete notes ID operation
func NewDeleteNotesID(ctx *middleware.Context, handler DeleteNotesIDHandler) *DeleteNotesID {
	return &DeleteNotesID{Context: ctx, Handler: handler}
}

/*
	DeleteNotesID swagger:route DELETE /notes/{id} notes deleteNotesId

# DeleteNote

delete note
*/
type DeleteNotesID struct {
	Context *middleware.Context
	Handler DeleteNotesIDHandler
}

func (o *DeleteNotesID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteNotesIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
