// Code generated by go-swagger; DO NOT EDIT.

package notes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetNotesIDHandlerFunc turns a function with the right signature into a get notes ID handler
type GetNotesIDHandlerFunc func(GetNotesIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetNotesIDHandlerFunc) Handle(params GetNotesIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetNotesIDHandler interface for that can handle valid get notes ID params
type GetNotesIDHandler interface {
	Handle(GetNotesIDParams, interface{}) middleware.Responder
}

// NewGetNotesID creates a new http.Handler for the get notes ID operation
func NewGetNotesID(ctx *middleware.Context, handler GetNotesIDHandler) *GetNotesID {
	return &GetNotesID{Context: ctx, Handler: handler}
}

/*
	GetNotesID swagger:route GET /notes/{id} notes getNotesId

# GetNote

get note
*/
type GetNotesID struct {
	Context *middleware.Context
	Handler GetNotesIDHandler
}

func (o *GetNotesID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetNotesIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
