// Code generated by go-swagger; DO NOT EDIT.

package notes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetNotesHandlerFunc turns a function with the right signature into a get notes handler
type GetNotesHandlerFunc func(GetNotesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetNotesHandlerFunc) Handle(params GetNotesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetNotesHandler interface for that can handle valid get notes params
type GetNotesHandler interface {
	Handle(GetNotesParams, interface{}) middleware.Responder
}

// NewGetNotes creates a new http.Handler for the get notes operation
func NewGetNotes(ctx *middleware.Context, handler GetNotesHandler) *GetNotes {
	return &GetNotes{Context: ctx, Handler: handler}
}

/*
	GetNotes swagger:route GET /notes notes getNotes

# GetAllNotes

get all notes
*/
type GetNotes struct {
	Context *middleware.Context
	Handler GetNotesHandler
}

func (o *GetNotes) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetNotesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
