// Code generated by go-swagger; DO NOT EDIT.

package notes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetNotesIDOKCode is the HTTP code returned for type GetNotesIDOK
const GetNotesIDOKCode int = 200

/*
GetNotesIDOK OK

swagger:response getNotesIdOK
*/
type GetNotesIDOK struct {
}

// NewGetNotesIDOK creates GetNotesIDOK with default headers values
func NewGetNotesIDOK() *GetNotesIDOK {

	return &GetNotesIDOK{}
}

// WriteResponse to the client
func (o *GetNotesIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetNotesIDBadRequestCode is the HTTP code returned for type GetNotesIDBadRequest
const GetNotesIDBadRequestCode int = 400

/*
GetNotesIDBadRequest Bad Request

swagger:response getNotesIdBadRequest
*/
type GetNotesIDBadRequest struct {
}

// NewGetNotesIDBadRequest creates GetNotesIDBadRequest with default headers values
func NewGetNotesIDBadRequest() *GetNotesIDBadRequest {

	return &GetNotesIDBadRequest{}
}

// WriteResponse to the client
func (o *GetNotesIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetNotesIDInternalServerErrorCode is the HTTP code returned for type GetNotesIDInternalServerError
const GetNotesIDInternalServerErrorCode int = 500

/*
GetNotesIDInternalServerError Internal Server Error

swagger:response getNotesIdInternalServerError
*/
type GetNotesIDInternalServerError struct {
}

// NewGetNotesIDInternalServerError creates GetNotesIDInternalServerError with default headers values
func NewGetNotesIDInternalServerError() *GetNotesIDInternalServerError {

	return &GetNotesIDInternalServerError{}
}

// WriteResponse to the client
func (o *GetNotesIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
