// Code generated by go-swagger; DO NOT EDIT.

package notes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PatchNotesIDOKCode is the HTTP code returned for type PatchNotesIDOK
const PatchNotesIDOKCode int = 200

/*
PatchNotesIDOK OK

swagger:response patchNotesIdOK
*/
type PatchNotesIDOK struct {
}

// NewPatchNotesIDOK creates PatchNotesIDOK with default headers values
func NewPatchNotesIDOK() *PatchNotesIDOK {

	return &PatchNotesIDOK{}
}

// WriteResponse to the client
func (o *PatchNotesIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PatchNotesIDBadRequestCode is the HTTP code returned for type PatchNotesIDBadRequest
const PatchNotesIDBadRequestCode int = 400

/*
PatchNotesIDBadRequest Bad Request

swagger:response patchNotesIdBadRequest
*/
type PatchNotesIDBadRequest struct {
}

// NewPatchNotesIDBadRequest creates PatchNotesIDBadRequest with default headers values
func NewPatchNotesIDBadRequest() *PatchNotesIDBadRequest {

	return &PatchNotesIDBadRequest{}
}

// WriteResponse to the client
func (o *PatchNotesIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PatchNotesIDInternalServerErrorCode is the HTTP code returned for type PatchNotesIDInternalServerError
const PatchNotesIDInternalServerErrorCode int = 500

/*
PatchNotesIDInternalServerError Internal Server Error

swagger:response patchNotesIdInternalServerError
*/
type PatchNotesIDInternalServerError struct {
}

// NewPatchNotesIDInternalServerError creates PatchNotesIDInternalServerError with default headers values
func NewPatchNotesIDInternalServerError() *PatchNotesIDInternalServerError {

	return &PatchNotesIDInternalServerError{}
}

// WriteResponse to the client
func (o *PatchNotesIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
