// Code generated by go-swagger; DO NOT EDIT.

package notes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostNotesCreatedCode is the HTTP code returned for type PostNotesCreated
const PostNotesCreatedCode int = 201

/*
PostNotesCreated Created

swagger:response postNotesCreated
*/
type PostNotesCreated struct {
}

// NewPostNotesCreated creates PostNotesCreated with default headers values
func NewPostNotesCreated() *PostNotesCreated {

	return &PostNotesCreated{}
}

// WriteResponse to the client
func (o *PostNotesCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostNotesBadRequestCode is the HTTP code returned for type PostNotesBadRequest
const PostNotesBadRequestCode int = 400

/*
PostNotesBadRequest Bad Request

swagger:response postNotesBadRequest
*/
type PostNotesBadRequest struct {
}

// NewPostNotesBadRequest creates PostNotesBadRequest with default headers values
func NewPostNotesBadRequest() *PostNotesBadRequest {

	return &PostNotesBadRequest{}
}

// WriteResponse to the client
func (o *PostNotesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostNotesInternalServerErrorCode is the HTTP code returned for type PostNotesInternalServerError
const PostNotesInternalServerErrorCode int = 500

/*
PostNotesInternalServerError Internal Server Error

swagger:response postNotesInternalServerError
*/
type PostNotesInternalServerError struct {
}

// NewPostNotesInternalServerError creates PostNotesInternalServerError with default headers values
func NewPostNotesInternalServerError() *PostNotesInternalServerError {

	return &PostNotesInternalServerError{}
}

// WriteResponse to the client
func (o *PostNotesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
