// Code generated by go-swagger; DO NOT EDIT.

package notes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostNotesHandlerFunc turns a function with the right signature into a post notes handler
type PostNotesHandlerFunc func(PostNotesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostNotesHandlerFunc) Handle(params PostNotesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostNotesHandler interface for that can handle valid post notes params
type PostNotesHandler interface {
	Handle(PostNotesParams, interface{}) middleware.Responder
}

// NewPostNotes creates a new http.Handler for the post notes operation
func NewPostNotes(ctx *middleware.Context, handler PostNotesHandler) *PostNotes {
	return &PostNotes{Context: ctx, Handler: handler}
}

/*
	PostNotes swagger:route POST /notes notes postNotes

# CreateNote

create note
*/
type PostNotes struct {
	Context *middleware.Context
	Handler PostNotesHandler
}

func (o *PostNotes) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostNotesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
