// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostAuthRegisterCreatedCode is the HTTP code returned for type PostAuthRegisterCreated
const PostAuthRegisterCreatedCode int = 201

/*
PostAuthRegisterCreated Created

swagger:response postAuthRegisterCreated
*/
type PostAuthRegisterCreated struct {
}

// NewPostAuthRegisterCreated creates PostAuthRegisterCreated with default headers values
func NewPostAuthRegisterCreated() *PostAuthRegisterCreated {

	return &PostAuthRegisterCreated{}
}

// WriteResponse to the client
func (o *PostAuthRegisterCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostAuthRegisterBadRequestCode is the HTTP code returned for type PostAuthRegisterBadRequest
const PostAuthRegisterBadRequestCode int = 400

/*
PostAuthRegisterBadRequest Bad Request

swagger:response postAuthRegisterBadRequest
*/
type PostAuthRegisterBadRequest struct {
}

// NewPostAuthRegisterBadRequest creates PostAuthRegisterBadRequest with default headers values
func NewPostAuthRegisterBadRequest() *PostAuthRegisterBadRequest {

	return &PostAuthRegisterBadRequest{}
}

// WriteResponse to the client
func (o *PostAuthRegisterBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostAuthRegisterInternalServerErrorCode is the HTTP code returned for type PostAuthRegisterInternalServerError
const PostAuthRegisterInternalServerErrorCode int = 500

/*
PostAuthRegisterInternalServerError Internal Server Error

swagger:response postAuthRegisterInternalServerError
*/
type PostAuthRegisterInternalServerError struct {
}

// NewPostAuthRegisterInternalServerError creates PostAuthRegisterInternalServerError with default headers values
func NewPostAuthRegisterInternalServerError() *PostAuthRegisterInternalServerError {

	return &PostAuthRegisterInternalServerError{}
}

// WriteResponse to the client
func (o *PostAuthRegisterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
