// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostAuthLoginOKCode is the HTTP code returned for type PostAuthLoginOK
const PostAuthLoginOKCode int = 200

/*
PostAuthLoginOK OK

swagger:response postAuthLoginOK
*/
type PostAuthLoginOK struct {
}

// NewPostAuthLoginOK creates PostAuthLoginOK with default headers values
func NewPostAuthLoginOK() *PostAuthLoginOK {

	return &PostAuthLoginOK{}
}

// WriteResponse to the client
func (o *PostAuthLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostAuthLoginBadRequestCode is the HTTP code returned for type PostAuthLoginBadRequest
const PostAuthLoginBadRequestCode int = 400

/*
PostAuthLoginBadRequest Bad Request

swagger:response postAuthLoginBadRequest
*/
type PostAuthLoginBadRequest struct {
}

// NewPostAuthLoginBadRequest creates PostAuthLoginBadRequest with default headers values
func NewPostAuthLoginBadRequest() *PostAuthLoginBadRequest {

	return &PostAuthLoginBadRequest{}
}

// WriteResponse to the client
func (o *PostAuthLoginBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostAuthLoginInternalServerErrorCode is the HTTP code returned for type PostAuthLoginInternalServerError
const PostAuthLoginInternalServerErrorCode int = 500

/*
PostAuthLoginInternalServerError Internal Server Error

swagger:response postAuthLoginInternalServerError
*/
type PostAuthLoginInternalServerError struct {
}

// NewPostAuthLoginInternalServerError creates PostAuthLoginInternalServerError with default headers values
func NewPostAuthLoginInternalServerError() *PostAuthLoginInternalServerError {

	return &PostAuthLoginInternalServerError{}
}

// WriteResponse to the client
func (o *PostAuthLoginInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
