// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/almalii/swagger-contracts/restapi/operations/auth"
	"github.com/almalii/swagger-contracts/restapi/operations/notes"
	"github.com/almalii/swagger-contracts/restapi/operations/users"
)

// NewNotesAPIAPI creates a new NotesAPI instance
func NewNotesAPIAPI(spec *loads.Document) *NotesAPIAPI {
	return &NotesAPIAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		NotesDeleteNotesIDHandler: notes.DeleteNotesIDHandlerFunc(func(params notes.DeleteNotesIDParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation notes.DeleteNotesID has not yet been implemented")
		}),
		UsersDeleteUsersHandler: users.DeleteUsersHandlerFunc(func(params users.DeleteUsersParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation users.DeleteUsers has not yet been implemented")
		}),
		NotesGetNotesHandler: notes.GetNotesHandlerFunc(func(params notes.GetNotesParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation notes.GetNotes has not yet been implemented")
		}),
		NotesGetNotesIDHandler: notes.GetNotesIDHandlerFunc(func(params notes.GetNotesIDParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation notes.GetNotesID has not yet been implemented")
		}),
		UsersGetUsersHandler: users.GetUsersHandlerFunc(func(params users.GetUsersParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation users.GetUsers has not yet been implemented")
		}),
		NotesPatchNotesIDHandler: notes.PatchNotesIDHandlerFunc(func(params notes.PatchNotesIDParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation notes.PatchNotesID has not yet been implemented")
		}),
		UsersPatchUsersHandler: users.PatchUsersHandlerFunc(func(params users.PatchUsersParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation users.PatchUsers has not yet been implemented")
		}),
		AuthPostAuthLoginHandler: auth.PostAuthLoginHandlerFunc(func(params auth.PostAuthLoginParams) middleware.Responder {
			return middleware.NotImplemented("operation auth.PostAuthLogin has not yet been implemented")
		}),
		AuthPostAuthRegisterHandler: auth.PostAuthRegisterHandlerFunc(func(params auth.PostAuthRegisterParams) middleware.Responder {
			return middleware.NotImplemented("operation auth.PostAuthRegister has not yet been implemented")
		}),
		NotesPostNotesHandler: notes.PostNotesHandlerFunc(func(params notes.PostNotesParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation notes.PostNotes has not yet been implemented")
		}),

		// Applies when the "Authorization" header is set
		JWTAuthAuth: func(token string) (interface{}, error) {
			return nil, errors.NotImplemented("api key auth (JWTAuth) Authorization from header param [Authorization] has not yet been implemented")
		},
		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*NotesAPIAPI This is a sample notes-rew server. */
type NotesAPIAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// JWTAuthAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key Authorization provided in the header
	JWTAuthAuth func(string) (interface{}, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// NotesDeleteNotesIDHandler sets the operation handler for the delete notes ID operation
	NotesDeleteNotesIDHandler notes.DeleteNotesIDHandler
	// UsersDeleteUsersHandler sets the operation handler for the delete users operation
	UsersDeleteUsersHandler users.DeleteUsersHandler
	// NotesGetNotesHandler sets the operation handler for the get notes operation
	NotesGetNotesHandler notes.GetNotesHandler
	// NotesGetNotesIDHandler sets the operation handler for the get notes ID operation
	NotesGetNotesIDHandler notes.GetNotesIDHandler
	// UsersGetUsersHandler sets the operation handler for the get users operation
	UsersGetUsersHandler users.GetUsersHandler
	// NotesPatchNotesIDHandler sets the operation handler for the patch notes ID operation
	NotesPatchNotesIDHandler notes.PatchNotesIDHandler
	// UsersPatchUsersHandler sets the operation handler for the patch users operation
	UsersPatchUsersHandler users.PatchUsersHandler
	// AuthPostAuthLoginHandler sets the operation handler for the post auth login operation
	AuthPostAuthLoginHandler auth.PostAuthLoginHandler
	// AuthPostAuthRegisterHandler sets the operation handler for the post auth register operation
	AuthPostAuthRegisterHandler auth.PostAuthRegisterHandler
	// NotesPostNotesHandler sets the operation handler for the post notes operation
	NotesPostNotesHandler notes.PostNotesHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *NotesAPIAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *NotesAPIAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *NotesAPIAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *NotesAPIAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *NotesAPIAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *NotesAPIAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *NotesAPIAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *NotesAPIAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *NotesAPIAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the NotesAPIAPI
func (o *NotesAPIAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.JWTAuthAuth == nil {
		unregistered = append(unregistered, "AuthorizationAuth")
	}

	if o.NotesDeleteNotesIDHandler == nil {
		unregistered = append(unregistered, "notes.DeleteNotesIDHandler")
	}
	if o.UsersDeleteUsersHandler == nil {
		unregistered = append(unregistered, "users.DeleteUsersHandler")
	}
	if o.NotesGetNotesHandler == nil {
		unregistered = append(unregistered, "notes.GetNotesHandler")
	}
	if o.NotesGetNotesIDHandler == nil {
		unregistered = append(unregistered, "notes.GetNotesIDHandler")
	}
	if o.UsersGetUsersHandler == nil {
		unregistered = append(unregistered, "users.GetUsersHandler")
	}
	if o.NotesPatchNotesIDHandler == nil {
		unregistered = append(unregistered, "notes.PatchNotesIDHandler")
	}
	if o.UsersPatchUsersHandler == nil {
		unregistered = append(unregistered, "users.PatchUsersHandler")
	}
	if o.AuthPostAuthLoginHandler == nil {
		unregistered = append(unregistered, "auth.PostAuthLoginHandler")
	}
	if o.AuthPostAuthRegisterHandler == nil {
		unregistered = append(unregistered, "auth.PostAuthRegisterHandler")
	}
	if o.NotesPostNotesHandler == nil {
		unregistered = append(unregistered, "notes.PostNotesHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *NotesAPIAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *NotesAPIAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	result := make(map[string]runtime.Authenticator)
	for name := range schemes {
		switch name {
		case "JWTAuth":
			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, o.JWTAuthAuth)

		}
	}
	return result
}

// Authorizer returns the registered authorizer
func (o *NotesAPIAPI) Authorizer() runtime.Authorizer {
	return o.APIAuthorizer
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *NotesAPIAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *NotesAPIAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *NotesAPIAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the notes API API
func (o *NotesAPIAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *NotesAPIAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/notes/{id}"] = notes.NewDeleteNotesID(o.context, o.NotesDeleteNotesIDHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/users"] = users.NewDeleteUsers(o.context, o.UsersDeleteUsersHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/notes"] = notes.NewGetNotes(o.context, o.NotesGetNotesHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/notes/{id}"] = notes.NewGetNotesID(o.context, o.NotesGetNotesIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/users"] = users.NewGetUsers(o.context, o.UsersGetUsersHandler)
	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/notes/{id}"] = notes.NewPatchNotesID(o.context, o.NotesPatchNotesIDHandler)
	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/users"] = users.NewPatchUsers(o.context, o.UsersPatchUsersHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/auth/login"] = auth.NewPostAuthLogin(o.context, o.AuthPostAuthLoginHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/auth/register"] = auth.NewPostAuthRegister(o.context, o.AuthPostAuthRegisterHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/notes"] = notes.NewPostNotes(o.context, o.NotesPostNotesHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *NotesAPIAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *NotesAPIAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *NotesAPIAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *NotesAPIAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *NotesAPIAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[um][path] = builder(h)
	}
}
