// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Notes-Service API
//
//	This is a sample notes-rew server.
//	Schemes:
//	  http
//	Host: localhost:8081
//	BasePath: /
//	Version: 1.0
//	Contact:
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
