// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ControllerSignUpRequest controller sign up request
//
// swagger:model controller.SignUpRequest
type ControllerSignUpRequest struct {

	// email
	// Required: true
	// Max Length: 254
	// Min Length: 5
	Email *string `json:"email"`

	// password
	// Required: true
	Password *string `json:"password"`

	// username
	// Required: true
	// Max Length: 20
	// Min Length: 3
	Username *string `json:"username"`
}

// Validate validates this controller sign up request
func (m *ControllerSignUpRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUsername(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ControllerSignUpRequest) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("email", "body", m.Email); err != nil {
		return err
	}

	if err := validate.MinLength("email", "body", *m.Email, 5); err != nil {
		return err
	}

	if err := validate.MaxLength("email", "body", *m.Email, 254); err != nil {
		return err
	}

	return nil
}

func (m *ControllerSignUpRequest) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	return nil
}

func (m *ControllerSignUpRequest) validateUsername(formats strfmt.Registry) error {

	if err := validate.Required("username", "body", m.Username); err != nil {
		return err
	}

	if err := validate.MinLength("username", "body", *m.Username, 3); err != nil {
		return err
	}

	if err := validate.MaxLength("username", "body", *m.Username, 20); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this controller sign up request based on context it is used
func (m *ControllerSignUpRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ControllerSignUpRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ControllerSignUpRequest) UnmarshalBinary(b []byte) error {
	var res ControllerSignUpRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
