// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ControllerUpdateUserRequest controller update user request
//
// swagger:model controller.UpdateUserRequest
type ControllerUpdateUserRequest struct {

	// email
	// Required: true
	// Max Length: 254
	// Min Length: 5
	Email *string `json:"email"`

	// password
	// Required: true
	Password *string `json:"password"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this controller update user request
func (m *ControllerUpdateUserRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ControllerUpdateUserRequest) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("email", "body", m.Email); err != nil {
		return err
	}

	if err := validate.MinLength("email", "body", *m.Email, 5); err != nil {
		return err
	}

	if err := validate.MaxLength("email", "body", *m.Email, 254); err != nil {
		return err
	}

	return nil
}

func (m *ControllerUpdateUserRequest) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this controller update user request based on context it is used
func (m *ControllerUpdateUserRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ControllerUpdateUserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ControllerUpdateUserRequest) UnmarshalBinary(b []byte) error {
	var res ControllerUpdateUserRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
