// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ControllerSignInRequest controller sign in request
//
// swagger:model controller.SignInRequest
type ControllerSignInRequest struct {

	// email
	// Required: true
	// Max Length: 254
	// Min Length: 5
	Email *string `json:"email"`

	// password
	// Required: true
	// Max Length: 30
	// Min Length: 6
	Password *string `json:"password"`
}

// Validate validates this controller sign in request
func (m *ControllerSignInRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ControllerSignInRequest) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("email", "body", m.Email); err != nil {
		return err
	}

	if err := validate.MinLength("email", "body", *m.Email, 5); err != nil {
		return err
	}

	if err := validate.MaxLength("email", "body", *m.Email, 254); err != nil {
		return err
	}

	return nil
}

func (m *ControllerSignInRequest) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	if err := validate.MinLength("password", "body", *m.Password, 6); err != nil {
		return err
	}

	if err := validate.MaxLength("password", "body", *m.Password, 30); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this controller sign in request based on context it is used
func (m *ControllerSignInRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ControllerSignInRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ControllerSignInRequest) UnmarshalBinary(b []byte) error {
	var res ControllerSignInRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
